language: python
python: 3.4

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install -y xorg libxinerama-dev libcairo2-dev python-gi python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-glib-2.0 gdb

install:
  - pip3 install ".[test]"

before_script:
- ulimit -c unlimited -S       # enable core dumps

# FIXME: Tests cause SIGSEGV on Travis.
script:
  - true
  # - py.test

after_failure:
- COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
- if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" /usr/bin/python3 -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

# deploy:
#   provider: pypi
#   user: P403n1x87
#   password: $PYPI_PASSWORD
#   distributions: "sdist"
#   on:
#     tags: true
